#pragma once

// Configuration for SMENETE board

#define RETARGET_SPI_UART      USART1
#define RETARGET_SPI_CLOCK     cmuClock_USART1
#define RETARGET_SPI_MISO_PORT gpioPortC
#define RETARGET_SPI_MISO_PIN  10
#define RETARGET_SPI_MOSI_PORT gpioPortC
#define RETARGET_SPI_MOSI_PIN  8
#define RETARGET_SPI_SCK_PORT  gpioPortC
#define RETARGET_SPI_SCK_PIN   7
#define RETARGET_SPI_CS_PORT   gpioPortC
#define RETARGET_SPI_CS_PIN    11
#define RETARGET_SPI_WP_PORT   gpioPortC
#define RETARGET_SPI_WP_PIN    9
#define RETARGET_SPI_RX_LOC    USART_ROUTELOC0_RXLOC_LOC14
#define RETARGET_SPI_TX_LOC    USART_ROUTELOC0_TXLOC_LOC13
#define RETARGET_SPI_CLK_LOC   USART_ROUTELOC0_CLKLOC_LOC10
